### ISSUE TITLE
Bump to Ruby 3.1?

### ISSUE THREAD

**Issue by jeffwidman** [jonabc/licensed-ci#178]
I noticed the Readme and other places reference Ruby 2.6... what's holding back the upgrade to 3.1? Esp since these are actions workflows, IIUC they are isolated and don't require the target application source code to be upgraded...

**Comment by jonabc** [comment]
I don't think anything is holding back the upgrade. I ended up standardizing the Ruby version to whatever was the latest working version from the [repo network of ruby-packer](https://github.com/pmq20/ruby-packer/network).  Ruby packer is used to build the no-ruby distributions of github/licensed, but the project looks to be largely abandoned and I've yet to find a decent replacement or alternative.

So there's nothing blocking the version upgrade but I don't know that there's anything specifically requiring it either?
