### ISSUE TITLE
Error running `git add` on an empty directory

### ISSUE THREAD

**Issue by mhagger** [jonabc/licensed-ci#46]
I experienced a problem today with the latest release. I have a Go repo that has several directories `cmd/X`, `cmd/Y`, etc. that build different executables. I recently added a new such directory, for a new command (call it `Z`) that doesn't have any external dependencies. When I pushed that branch, I got an error like the following:

```
git add -- /home/runner/work/my/repo/.licenses/. /home/runner/work/my/repo/.licenses/X /home/runner/work/my/repo/.licenses/Y /home/runner/work/my/repo/.licenses/Z
fatal: pathspec '/home/runner/work/my/repo/.licenses/Z' did not match any files
Error: The process 'git' failed with exit code 128
```

This failure caused the action to fail without creating a PR to add the required license information.

ISTM that licensed-ci should do something like check which directories have contents and only pass those to `git add`, or alternatively perhaps run `git add -- /home/runnier/work/my/repo/.licenses` to add all existing directories at once. Note that `git add --ignore-missing` unfortunately _cannot_ be used to get around the problem, since that option is only allowed when `--dry-run` is also specified.

I was able to work around the problem by creating the missing directories by adding empty `.gitignore` files to them, but obviously it would be nice if this weren't necessary.

**Comment by gudmundur** [comment]
I naively worked around this issue on a PR I had by adding `.empty` files to those directories so that the Action would complete. An example of [this error is here](https://github.com/github/gitrpcd/runs/1391177453).

**Comment by gudmundur** [comment]
I naively worked around this issue on a PR I had by adding `.empty` files to those directories so that the Action would complete.

**Comment by jonabc** [comment]
> ISTM that licensed-ci should do something like check which directories have contents and only pass those to `git add`, or alternatively perhaps run `git add -- /home/runnier/work/my/repo/.licenses` to add all existing directories at once.

The complication with this approach is that while licensed only creates and moderates the specific cache paths, and if for whatever reason there are files under `.licenses` that are not managed by licensed-ci there can be unexpected side effects to performing git operations over the entire folder.

I'm not sure how much real-world risk there is for that scenario, but it seems relatively easy to check whether directories are empty or not.  I'll dig in a bit further but if this isn't blocking it probably won't be addressed too quickly.
