### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by schmidtw** [jonabc/licensed-ci#59]
We're seeing an `ERROR` while installing a gem from the looks of it.  This happens for both 2.x and 3.x.

```
Run jonabc/setup-licensed@v1
  with:
    version: 3.x
    install-dir: /usr/local/bin
attempting to install licensed gem matching "3.x"
/usr/bin/gem list licensed --exact --remote --all --quiet
licensed (3.0.0, 2.15.2, 2.15.1, 2.15.0, 2.14.4, 2.14.3, 2.14.2, 2.14.1, 2.14.0, 2.13.0, 2.12.2, 2.12.1, 2.12.0, 2.11.1, 2.11.0, 2.10.0, 2.9.2, 2.9.1, 2.9.0, 2.8.0, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.0, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.0, 2.0.1, 2.0.0, 1.5.2, 1.5.1, 1.4.0, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.0, 1.1.0, 1.0.1, 1.0.0, 0.11.1, 0.11.0, 0.10.0, 0.6.0)
/usr/bin/gem install licensed -v 3.0.0
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.7.0 directory.
gem installation was not successful
attempting to install licensed executable matching "3.x"
sudo /usr/bin/tar xzv -f /tmp/JAeIhF/licensed.tar.gz -C /usr/local/bin ./licensed
./licensed
licensed (3.0.0) executable installed
```

Happy to help provide more debugging information if needed.

**Comment by jonabc** [comment]
Hi @schmidtw thanks for logging this - does your action workflow still run or do you have later problems running licensed?  The error itself comes from `/usr/bin/gem` and is handled but I left the output going to the action log for transparency.  If you're specifically interested in installing licensed as a gem, please run [ruby/setup-ruby](https://github.com/ruby/setup-ruby) in your workflow before jonabc/setup-licensed.

To give a little more context, licensed is distributed in two different ways - as a ruby gem and as a standalone executable.  They each have drawbacks in usage
- the gem needs a local ruby installation but has the widest compatibility
- the executables do not need a local ruby installation but are incompatible with enumerating bundler (ruby gem) dependencies.

I'm going to close this as it's not an error that affects the actions functionality, but I'm happy to answer any other questions.
