### ISSUE TITLE
V1.5.5 broke our flow

### ISSUE THREAD

**Issue by nadavshatz** [jonabc/licensed-ci#96]
Hi, since the release of V1.5.5 we've been seeing the following errors whenever the action tries to create a new branch for licenses:

```
/usr/bin/git fetch licensed-ci-origin enh/fix-sidekiq-sessions-licenses
fatal: could not read Password for 'https://***@github.com': No such device or address
/usr/bin/git fetch licensed-ci-origin enh/fix-sidekiq-sessions
fatal: could not read Password for 'https://***@github.com': No such device or address
/usr/bin/git checkout --track licensed-ci-origin/enh/fix-sidekiq-sessions-licenses
fatal: 'licensed-ci-origin/enh/fix-sidekiq-sessions-licenses' is not a commit and a branch 'enh/fix-sidekiq-sessions-licenses' cannot be created from it
/usr/bin/git checkout --track licensed-ci-origin/enh/fix-sidekiq-sessions
fatal: 'licensed-ci-origin/enh/fix-sidekiq-sessions' is not a commit and a branch 'enh/fix-sidekiq-sessions' cannot be created from it
```

Can you please advise on what we need to do to fix this? or better yet roll forward a non breaking fix for the patch version release?

Thanks!

**Comment by nadavshatz** [comment]
@jonabc thank you for the prompt reply and for all the work on this great action! really appreciated.

This is our (simple) setup:
```yaml
      - uses: jonabc/licensed-ci@v1
        with:
          workflow: branch
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by jonabc** [comment]
@nadavshatz do you use `actions/checkout` and if so do you set a custom token on that?

**Comment by jonabc** [comment]
One other question, in the logs do you see any errors around a `git remote add` statement?

**Comment by nadavshatz** [comment]
```
      - uses: actions/checkout@v1
```
no custom token. I think we stick to v1 for the licensing stuff so it doesn't have issues with v2.

as for the logs:
```
/usr/bin/git config user.name licensed-ci
/usr/bin/git config user.email licensed-ci@users.noreply.github.com
/usr/bin/git remote add licensed-ci-origin https://***@github.com/TailorBrands/repo-name


/opt/hostedtoolcache/Ruby/2.6.5/x64/bin/licensed status -c .licensed.yml
```

nothing really. then it properly runs and finishes with:

```

121 dependencies checked, 2 errors found.

Licensed found errors during source enumeration.  Please see https://github.com/github/licensed/tree/master/docs/commands/status.md#status-errors-and-resolutions for possible resolutions.
```

**Comment by nadavshatz** [comment]
@jonabc any thoughts about next steps we can take except hardcoding v1.5.4?

**Comment by jonabc** [comment]
@nadavshatz sorry I'm juggling a few things at the moment and haven't had a chance to really take a look.  I've pushed up a quick test on what [I think is the most likely cause](https://github.com/jonabc/licensed-ci/commit/9f64c9003a558fbd9b2601198519e67db8e148d8) - can you hardcode your action to `jonabc/licensed-ci@revert-xaccesstoken` to see if that fixes it?  If it does I'll put that up as a PR and publish a new release when I get a chance.

**Comment by nadavshatz** [comment]
@jonabc Working!

I had a feeling this was related reading over the changes in `1.5.5` but wasn't sure if this was intentional.

A new release would be greatly appreciated 🙏🏼  If I can assist with a PR or anything of the like just let me know. don't wanna step on your toes.

Cheers 🍻

**Comment by jonabc** [comment]
No problem at all!  If that's all that's needed I'll get the release out shortly.  Thanks for helping test that 🙇

**Comment by jonabc** [comment]
[v1.5.7 released](https://github.com/jonabc/licensed-ci/releases/tag/v1.5.7) with the fix

**Comment by nadavshatz** [comment]
Thanks!
